### ISSUE TITLE
Support to use Git tags as versions

### ISSUE THREAD

**Issue by filips123** [fregante/browser-extension-template#1]
Add support to auto-release extension on Git tags and use that Git tag as version.

**Comment by notlmn** [comment]
This template provides basic auto-versioning and auto-publishing so that the user doesn't have to manually interfere with the release cycle.

But that mostly sounds like doing manual-releases, while this template aims at "auto" releases.

Maybe we could add documentation on how to setup publishing on tags, i.e. manual releases. What do you think?

**Comment by filips123** [comment]
> But that mostly sounds like doing manual-releases, while this template aims at "auto" releases.

Not necessarily. Many developers use GitHub releases if they want better versioning management. And even if GitHub release and tag is created manually, extension would be published automatically to all web stores. And this is also main feature that developers would want.

> Maybe we could add documentation on how to setup publishing on tags, i.e. manual releases. What do you think?

I think that `.travis.yml` needs to check environment variable called something like `RELEASE_ON_TAGS` which should determine if extension should be released on tags.

If it is true, it should only release extension on tagged builds with version from Git tag.
If it is false, it should release extension only on not tagged builds with version from date, as it currently does.

**Comment by notlmn** [comment]
I understand what you mean, having tagged releases is great.

But what I'm saying is that is not a bug in this "template", it could be an additional thing to be mentioned in the readme that the extension author could be made aware. Something like best practices for managing releases.

PRs welcome to add it to the documentation or to the actual Travis file if you have an actual implementation.
