### ISSUE TITLE
Content scripts injected via chrome.scripting API

### ISSUE THREAD

**Issue by onikienko** [fregante/browser-extension-template#100]
It looks like `@parcel/config-webextension` does not cover `chrome.scripting` API.

What if I need to inject scripts and styles dynamically like in the code below?

```javaScript
chrome.scripting
    .executeScript({
      target : {tabId},
      files : [ "checker/index.js" ],
    })

chrome.scripting
    .insertCSS({
      target : {tabId},
      files : [ "checker/index.css" ],
    })
```

**Comment by fregante** [comment]
See this: https://github.com/parcel-bundler/parcel/issues/5758#issuecomment-1204354170

**Comment by onikienko** [comment]
Thank you for your answer, @fregante 
But I don't think that code like that will work.

```javaScript
import contentScript from "url:./checker/index.js";

chrome.scripting
    .executeScript({
      target : {tabId},
      files : [ contentScript ],
    })
```

`contentScript` will look like `chrome-extension://extensionID/contentScript.234h234234.js` while `file` for `chrome.scripting.executeScript` should be a path from the extension root. In that case `contentScript.234h234234.js`.
