### ISSUE TITLE
Disabling HMR in parcel breaks automatic reloading for web-ext with Google Chrome

### ISSUE THREAD

**Issue by MaskyS** [fregante/browser-extension-template#104]
Same issue as #68, where simply reloading the page doesn't reflect any changes. Removing `--no-hmr` flag from [manifest.json](https://github.com/fregante/browser-extension-template/blob/28339fce620f5e75ef6ee323e72cba3d90c7a745/package.json#L10) fixes the issue - though I'm not sure why. 

### Steps to reproduce 
Clone repo 
`npm install`, `npm run watch`
Run `web-ext run -t chromium` (with Google Chrome as default browser)
Make a change anywhere - the console log `content.js` or the  "Set a text!" string in `source/options-storage.js`
Reload the page
The text/log will not change
Only doing Ctrl-C and restarting web-ext will produce an update

### Environment details 
```
Using commit 28339fce620f5e75ef6ee323e72cba3d90c7a745
MacOS Monterey 12.3 (21E230)
Chrome Version 126.0.6478.127 (Official Build) (x86_64)

"@parcel/config-webextension": "^2.12.1-canary.3290",

npx parcel -V
2.0.0-canary.1665+b4fcf7098
```

**Comment by fregante** [comment]
HMR and web-ext are unrelated and completely at odds with each other, so this cannot be correct. 

web-ext will disable and re-enable the extension, this breaks any existing content scripts and will close any chrome-extension:// pages. It's 100% impossible to achieve HMR if the tab closes. 

You can re-enable HMR if it works for you, but you'll have to disable auto reloading in web-ext. 

The issue you're most likely describing is just web-ext failing to reload after a while—again this is unrelated to HMR and unrelated to this template, so I'm closing this issue.
