### ISSUE TITLE
Enable travis on this repo

### ISSUE THREAD

**Issue by fregante** [fregante/browser-extension-template#11]
Travis should be enabled so the linting is applied to this template, to ensure that the code works.

You could even set up the extension and publish it "privately" (unlisted) on the stores, to ensure that everything works.

**Comment by notlmn** [comment]
Done!

------------

> You could even set up the extension and publish it "privately" (unlisted) on the stores, to ensure that everything works.

That shouldn't be a problem, as no cron jobs will be set up.

(The first Travis build deployment was run because of "Trigger build").

**Comment by fregante** [comment]
> That shouldn't be a problem, as no cron jobs will be set up.

I mean it should work for people who will use this template. For us it's just an extra _lint_ to ensure we don't break it in the future.
