### ISSUE TITLE
Relicense more permissively

### ISSUE THREAD

**Issue by fregante** [fregante/browser-extension-template#16]
MIT means that users will have to include your license file:

> The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

But you don't have one. Perhaps this could use WTFPL or CC0 instead.

https://tldrlegal.com/license/do-wtf-you-want-to-public-license-v2-(wtfpl-2.0)
https://tldrlegal.com/license/creative-commons-cc0-1.0-universal

**Comment by notlmn** [comment]
I do find CC0 comfortable for content that is generally copy-pastable, or that is informative (like blogs and code snippets). And its what all of [awesome](https://github.com/sindresorhus/awesome) ecosystem uses.

I'd go with CC0 as there's the "no liability" claim in it, which I think is a very good option to choose considering the current privacy state of most browser extensions on the market.
