### ISSUE TITLE
`watch` script error after initial install

### ISSUE THREAD

**Issue by slikts** [fregante/browser-extension-template#22]
I cloned the repo, ran `npm i`, then `npm run watch`, and it exits with this error:
```
CopyPlugin Invalid Options

options.0 should be string
options.0.ignore should be array
options.0 should match some schema in anyOf
```
It's not clear what it's validating or what the steps to resolve this would be.

**Comment by ha-D** [comment]
There's an error in the `CopyWebpackPlugin` options which causes problems in newer versions of the plugin. This should fix it:

Open the webpack.config.js file and change the line

```js
new CopyWebpackPlugin([
	{
		...
		ignore: '*.js'
	},
	...
])
```

to:

```js
new CopyWebpackPlugin([
	{
		...
		ignore: ['*.js']
	},
	...
])
```

**Comment by fregante** [comment]
PR welcome
