### ISSUE TITLE
Deployment cronjob creates tag but it doesn't trigger `deploy-tag`

### ISSUE THREAD

**Issue by fregante** [fregante/browser-extension-template#25]
> There is a limitation of workflow: An action in a workflow run can't trigger a new workflow run. 

> I would suggest you use your own PAT when creating tags. You can store your PAT in secrets and use ${{ secrets.PATNAME } in your actions.
> ```yml
> env:
>   GITHUB_TOKEN: ${{ secrets.PATNAME }}

From: https://github.community/t5/GitHub-Actions/Github-actions-workflow-not-triggering-with-tag-push/m-p/39772#M3959

You can see this in [Refined GitHub’s Actions](https://github.com/sindresorhus/refined-github/actions). "Auto-tagger" ran but "Deployment" didn't follow it. Now I had to re-create the tag

<img width="878" alt="rgh" src="https://user-images.githubusercontent.com/1402241/78195069-175f1f80-747f-11ea-963e-2a33cc434334.png">

I think this only needs to be updated with instructions to use a custom personal token instead of the provided one.

**Comment by notlmn** [comment]
Added personal token to secrets with name `GH_TOKEN` (not `GITHUB_TOKEN`, which is reserved by GHA).

Lets use this repo for testing, I thinks we can change cron as we need.

**Comment by fregante** [comment]
That’s a slightly confusing name (too similar to the included token), in RG I proposed to store it as TAGGER_TOKEN to justify why it’s needed at all. 

Anyway that PR was merged so we can wait until April 4th to see if it works there.

**Comment by fregante** [comment]
RG finally create a new tag but it still didn't trigger the [`deploy-tag` workflow](https://github.com/sindresorhus/refined-github/actions?query=workflow%3ADeployment)

According to that forum, the problem was also that `@actions` was the tag committer, so maybe changing that would work. Sending a PR now

**Comment by fregante** [comment]
Still didn't work. ~~I may have found a better solution~~ _Nope._

Edit: I don't understand why it's not working... the docs say it should

**Comment by fregante** [comment]
The holy grail is here: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjobs_idoutputs

- Have a job detect the need for a release
- Have following jobs **depend on** that, and use it as a condition 🎉
