### ISSUE TITLE
Add installation instructions for Safari on macOS 11

### ISSUE THREAD

**Issue by notlmn** [fregante/browser-extension-template#31]
Related to https://github.com/sindresorhus/refined-github/issues/14.

Instructions for converting browser extension on [Apple developer documentation](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari) mentions that anyone can convert extension and basically sideload it into Safari.

I do not yet know how Apple intends to publish their extensions (maybe through App Store). Also I do not have an Apple developer account, even if I did, I'm sure that Apple would not want this extension on their store, even for testing.

Opening this issue to explore options on automating publishing (to App Store?), document any additional setup instructions on doing the same.

/cc @fregante.

**Comment by sindresorhus** [comment]
> I do not yet know how Apple intends to publish their extensions (maybe through App Store).

Yes, through the App Store.

> on automating publishing (to App Store?)

Fastline is the best bet for this. They have ready-made action for building and publishing: https://docs.fastlane.tools/getting-started/ios/appstore-deployment/

**Comment by fregante** [comment]
> I'm sure that Apple would not want this extension on their store, even for testing.

Given that Safari publishing can only be done by Mac developers that pay $99/year, it should very likely be disabled by default anyway. It could just be an extra `.github/workflows/deployment-safari.md` file with instructions.
