### ISSUE TITLE
Move to Parcel

### ISSUE THREAD

**Issue by fregante** [fregante/browser-extension-template#34]
Webpack. Enough said.

https://github.com/notlmn/browser-extension-template/blob/master/webpack.config.js
https://github.com/notlmn/browser-extension-template#configuration

Versus:

https://github.com/tanmayrajani/notifications-preview-github/blob/35accac48e28da78e0a5b86bc45c44c20f5f0d98/package.json#L6-L7

Here's a PR to take inspiration from: https://github.com/tanmayrajani/notifications-preview-github/pull/88/files

Issues:
- Works with Parcel v1, but Parcel 2 doesn't support web extensions the same way yet, but it's not even out yet
- I haven't figured out how to keep the polyfill separate and unchanged, I'm not sure it's possible: https://github.com/notlmn/browser-extension-template/blob/e6a5ae569d931214fc5e822c097ccb011c745a0f/webpack.config.js#L26

**Comment by notlmn** [comment]
Personally I don't mind having to have a configuration for my build system as long as it gets the job done. As much as I don't like some parts of webpack, it still gets the job done.

Parcel on the other hand promises to provide a zero-config solution, but when we ask for a little bit more flexibility it doesn't make sense anymore. We end up either specify configuration through command-line flags, or a separate file anyway.

So at the end, I'm indifferent.

**Comment by fregante** [comment]
> when we ask for a little bit more flexibility it doesn't make sense anymore

Absolutely true, in fact I have to run `parcel && babel` just to drop the comments because I couldn't find a way to do it otherwise.

However I'm tired of having to maintain an [increasingly-longer Webpack config](https://github.com/sindresorhus/hide-files-on-github/pull/99/files#diff-b0ba29b245f5327bca2d51ac8bbb0821). I'd rather have a _parcel one-liner_ and replace it with Webpack only when necessary.

**Comment by notlmn** [comment]
Are will still exploring Parcel with v1 or do we wait for Parcel v2 with better extension support and keep using webpack for now?

**Comment by fregante** [comment]
I think v1 with the extension offers better UX. The will support it in v2 eventually

**Comment by fregante** [comment]
This change would also facilitate and promote using JSX with dom-chef, which is arguably the best way to create DOM elements without XSS.
