### ISSUE TITLE
parcel watch - /distribution getting crammed with temp .css files

### ISSUE THREAD

**Issue by nikoisonfire** [fregante/browser-extension-template#47]
Using the default "watch" task and editing & saving CSS files works perfectly, except it cramms files in the /distribution directory as such

![image](https://user-images.githubusercontent.com/22169321/111910066-21977680-8a60-11eb-9a90-5b8f391e2cf7.png)

**Comment by fregante** [comment]
This isn’t something we can solve because we can’t make assumptions about the dist folder (i.e. I can’t just empty the folder) and that’s how Parcel works. You could add a `rm -rf dist &&` before each build and watch scripts or delete the folder manually every once in a while

**Comment by fregante** [comment]
Does anyone know of a way to ask git to clean untracked files from a specific directory? We can add that as `prewatch` and `prebuild`

**Comment by nikoisonfire** [comment]
Federico, for some reason it stopped generating tons of files using the watch task

![image](https://user-images.githubusercontent.com/22169321/116536305-0af90080-a8e5-11eb-9b88-156e641ef526.png)
