### ISSUE TITLE
Build improvements

### ISSUE THREAD

**Issue by fregante** [fregante/browser-extension-template#48]
Following https://github.com/fregante/browser-extension-template/pull/44

- [ ] Don't minify the CSS
- [x] include webext-base-css via `@import 'webext-base-css';`
- [ ] Flat output https://github.com/parcel-bundler/parcel/discussions/5858
- [ ] Somehow extract `webext-options-sync` to its own "vendor" entry so it's not bundled 3 times separately  https://github.com/parcel-bundler/parcel/issues/5859
- [x] Automatically include the `browser` global

The last one is feasible via:

https://github.com/pixiebrix/webext-messenger/blob/35961df965d1a75da941187ddcb67acdaeb82aec/test/demo-extension/manifest.json#L7

And 

https://github.com/pixiebrix/webext-messenger/blob/35961df965d1a75da941187ddcb67acdaeb82aec/.parcelrc#L4-L9

**Comment by fregante** [comment]
Some Parcel config can be copied from https://github.com/pixiebrix/webext-messenger/commit/2a4ab7da2b28e92757bda81ed71bcb188a23c736#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by losnappas** [comment]
I just used this template, and the "template cleanup" action failed. Not a big deal obviously, but a potential build improvement nonetheless.

https://github.com/losnappas/firefox-split-view/actions/runs/4562743709/jobs/8050344918
