### ISSUE TITLE
Is it possible to have the release workflow appear as a deployment?

### ISSUE THREAD

**Issue by fregante** [fregante/browser-extension-template#49]
Sometimes deployments fail and nobody notices. There are 2 ways to make them more visible:

- use GitHub deployments, somehow, they appear in their own section on GitHub
- include a badge somewhere in the readme

**Comment by fregante** [comment]
<img width="1123" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/115210408-bdcca000-a128-11eb-9159-3bc9ba7ed483.png">

It's possible and it looks great! https://docs.github.com/en/rest/reference/repos#create-a-deployment-status

But this might require a bit of code. I'm considering writing an action

**Comment by fregante** [comment]
https://github.com/fregante/compact-github-deployment-action

**Comment by gbdlin** [comment]
The link above is no longer working. As it is already used on the master branch in github actions workflow, the workflow is now broken.

**Comment by fregante** [comment]
Ah sorry about that. It seemed to work after I made it private, but it guess it stopped. The action wasn’t working as well as intended and I had to rewrite it, but it’s still not done. 

Could you send a PR to revert my last commit? I don’t have access to a computer right now

**Comment by fregante** [comment]
Undone in 9b1f180

**Comment by fregante** [comment]
It looks like GitHub added native support for this via `jobs.*.environment` property. See:

- https://github.com/refined-github/github-url-detection/deployments/activity_log?environment=github-pages
- https://github.com/refined-github/github-url-detection/blob/b93c1f18d7307f72943a95094f4c12127f3ca8c3/.github/workflows/demo.yml#L33-L35

That key likely creates a deployment and keeps track of it as part of the job’s lifecycle.

**Comment by fregante** [comment]
Sweet, it works!

- https://github.com/hankxdev/one-click-extensions-manager/deployments
- https://github.com/hankxdev/one-click-extensions-manager/pull/98

<img width="687" alt="Screenshot 5" src="https://user-images.githubusercontent.com/1402241/222427847-6fda8a1f-1a22-4c37-8c55-c3a989bdbda1.png">
