### ISSUE TITLE
Parcel building files outside of those defined in manifest.json

### ISSUE THREAD

**Issue by nikoisonfire** [fregante/browser-extension-template#50]
It would be great to be able to config parcel to also compile other files in the "/source"-dir such as other used .html/.js files

![image](https://user-images.githubusercontent.com/22169321/116538728-34675b80-a8e8-11eb-8393-3c148b583432.png)

In this example would be redirect.html and redirect.js but they are not compiled to /distribution, only the main files (options.../background...)

**Comment by nikoisonfire** [comment]
Closing this one myself *face-palm*. Sometimes I'm too fast to creating issues.

Changed the `package.json` watch task:

`
"watch": "parcel watch source/*.js source/*.html source/*.css source/manifest.json --dist-dir distribution --no-cache --no-hmr",
`

Maybe you want to add this to the documentation? I think could be helpful for some people :)

**Comment by fregante** [comment]
> redirect.html and redirect.js but they are not compiled to /distribution

What are those files? How do you use them?

**Comment by nikoisonfire** [comment]
My extension on a list of pages (in options) redirects to that `redirect.html` but I want that page to be able to communicate with my extension (sendMessage --> received in background.js), that's why this `redirect.js` exists

_(in a nutshell: user types in XYZ.com, gets redirect to the HTML, redirect makes the user do some stuff and then redirects back to the XYZ)_

Tried to use content-scripts and background-script as .html but both approaches weren't really working for my so I outsourced

**Comment by fregante** [comment]
> `"watch": "parcel watch source/*.js source/*.html source/*.css source/manifest.json --dist-dir distribution --no-cache --no-hmr",`

Doing this is not a good idea, just list only the files that are not found through `manifest.json`. In your case:

```
parcel watch source/manifest.json source/redirect.*
```
