### ISSUE TITLE
How to have parcel include onboarding/* into the build

### ISSUE THREAD

**Issue by janmechtel** [fregante/browser-extension-template#56]
How can I get the files in the folder `onboarding/` to be included in the build?

### Background

I'm trying to build a an onboarding according this to:
https://extensionworkshop.com/documentation/develop/onboard-upboard-offboard-users/#onboarding

For that I've included this in the `background.ts`:

```
const url = browser.runtime.getURL("onboarding/onboarding.html");
await browser.tabs.create({ url });
```

This works fine if the file is found. But for some reason, `parcel build`/ `parcel watch` are not including the onboarding.html file into the `distribution/` folder automatically.

I've tried finding a solution in parcel, but the only way I found is a copy. So for now I've worked around that by copy the files manually before the `watch`:

```
"copy-onboarding": "xcopy source\\onboarding\\ distribution\\onboarding\\ /y",
"watch": "npm run copy-onboarding && parcel watch source/manifest.json --dist-dir distribution --no-cache --no-hmr"
```

However that leads to other problems, because now I can't add a `onboarding.ts` file as it won't be build to `onboarding.js` and have it's dependencies bundled.

**Do you have an idea how to get parcel to include the files?**

**Comment by fregante** [comment]
You can specify that folder under `web_accessible_resources`. More details may be found in 

- https://github.com/parcel-bundler/parcel/issues/5758#issuecomment-772184560
- Also tracked locally in https://github.com/fregante/browser-extension-template/issues/46
