### ISSUE TITLE
Unrecognized manifest key 'applications'.

### ISSUE THREAD

**Issue by lyqht** [fregante/browser-extension-template#58]
Hello, I've found this template github repository through the MDN Web Docs :) 

When I tried generating a project and viewing it under "Load Unpacked" under the Google Chrome extensions, I see the following error

![image](https://user-images.githubusercontent.com/35736525/143728833-60f17f16-5485-4af2-80bc-521ec5e2a885.png)

**Comment by fregante** [comment]
Yes it's expected. That's Firefox-specific so Chrome doesn't know it. You can ignore it, it's not an error.

**Comment by Osiris-Team** [comment]
@fregante Have a similar issue, but I think it prevents the extension from getting enabled: 
![image](https://github.com/fregante/browser-extension-template/assets/59899645/a4bf9222-46f1-409a-be03-be2e6e3bded6)

![image](https://github.com/fregante/browser-extension-template/assets/59899645/43708f77-6402-43af-894c-b684345816ab)

Unrecognized manifest key 'browser_specific_settings'.
```json
{"name":"Awesome Extension","version":"0.0.0","description":"An awesome new browser extension","homepage_url":"https://github.com/fregante/browser-extension-template","manifest_version":3,"minimum_chrome_version":"100","browser_specific_settings":{"gecko":{"id":"awesome-extension@notlmn.github.io","strict_min_version":"100.0"}},"icons":{"128":"icon.082f75ba.png"},"permissions":["storage"],"host_permissions":["https://github.com/*"],"content_scripts":[{"matches":["https://chat.openai.com/c/*"],"js":["content.70a01fb4.js"],"css":["content.699ca3cc.css"],"run_at":"document_end"}],"options_ui":{"browser_style":true,"page":"options.e17f98f3.html"},"background":{"service_worker":"background.a054f291.js","type":"module"}}

```

**Comment by fregante** [comment]
The extension is enabled in your screenshot. Again, it's just a warning and it can be ignored. The toolbar icon is gray for unrelated reasons (regular extension behavior)
