### ISSUE TITLE
change project description from webpack to parcel

### ISSUE THREAD

**Issue by aarmn** [fregante/browser-extension-template#63]
I guess the title is trivial, 
📕 Barebones boilerplate with webpack, options handler, and auto-publishing
to
📕 Barebones boilerplate with parcel, options handler, and auto-publishing
and I posted a question in [here](https://github.com/parcel-bundler/parcel/discussions/7693) I would be glad if sb read that and tell me can this repo help me out with that or not.

**Comment by fregante** [comment]
Duplicate of #61
