### ISSUE TITLE
importing Image not working from content script

### ISSUE THREAD

**Issue by goldylucks** [fregante/browser-extension-template#67]
Don't know if it's an issue in the configuration or in parcel, but doing this doesn't work:

```
// source/react/OnBoarding/OnBoarding.jsx
import logo from "../../images/logo.png"

export default function OnBoarding() {
  return <img src={logo} className="logo-2" alt="Apollo Logo 2" />
}
```

it results in this:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/6963212/159031869-41804974-0833-46c2-95f7-5b8a678f2aa6.png">

however this does work:
```
const logo = browser.runtime.getURL("../../logo.f18a6316.png")
```

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/6963212/159032278-2efb5b79-12bc-400a-8c38-3266c2b9f6a9.png">

interestingly, this does work from an html page of the extension which I open upon installation of the extension:

```
// background.js
import browser from "webextension-polyfill"

browser.runtime.onInstalled.addListener(({ reason }) => {
	if (reason === browser.runtime.OnInstalledReason.INSTALL) {
		browser.tabs.create({
			url: browser.runtime.getURL("on-install/index.html"),
		})
	}
})

// source/on-install/App/App.jsx
import logo from "../../images/logo.png"

export default function OnBoardingApp() {
  return <img src={logo} />
}
```

<img width="842" alt="image" src="https://user-images.githubusercontent.com/6963212/159032777-6511b99f-dd6d-4279-92b1-ee0fb38699fb.png">

my manifest:

```
{
	"name": "Apollo",
	"version": "0.0.0",
	"description": "An awesome new browser extension",
	"homepage_url": "https://github.com/fregante/browser-extension-template",
	"manifest_version": 2,
	"minimum_chrome_version": "80",
	"applications": {
		"gecko": {
			"id": "awesome-extension@notlmn.github.io",
			"strict_min_version": "80.0"
		}
	},
	"icons": {
		"128": "icon.png"
	},
	"permissions": [
		"https://github.com/fregante/browser-extension-template/*",
		"tabs",
		"storage"
	],
	"content_scripts": [
		{
			"matches": [
				"<all_urls>",
				"https://*.zendesk.com/agent*",
				"https://*.zendesk.com/admin*"
			],
			"js": ["content.js"],
			"css": ["content.css"],
			"run_at": "document_end"
		}
	],
	"options_ui": {
		"chrome_style": true,
		"page": "options/options.html"
	},
	"background": {
		"persistent": false,
		"scripts": ["background.js"]
	},
	"web_accessible_resources": [
		"on-install/index.html",
		"logo.*.png",
		"images/logo.png",
		"images/logo.*.png",
		"images/*",
		"images/*.png"
	]
}

```

any ideas what I'm missing here?

Thanks for the awesome project!! 💜

**Comment by fregante** [comment]
A few pointers:

- You have to use getURL in the content script or else the URLs will be relative to the current website rather than the extension. This also explains why it works without it on an extension page
- it appears that getURL is "not supported" by parcel: https://github.com/parcel-bundler/parcel/issues/5758#issuecomment-772184560
- the getURL example with the hashed filename works because it's ignored by Parcel and you're providing the final URL to it, so it's natively supported by the browser

Have you tried this?

``` JavaScript 
import logo from "./blah blah/logo.png"

<img src={browser.runtime.getURL(logo)}/>
``` 

The `logo` variable will be set by Parcel to `"/logo.abcd56.png"` and that's a valid string to pass to getURL, you just need to make sure it points to the right element in the distribution folder (e.g. if it's inside images/, then also include that: `getURL("images/" + logo)`

**Comment by goldylucks** [comment]
that did the trick! 🚀

```
// manifest.json
"web_accessible_resources": ["on-install/index.html", "images/*"]

// OnBoarding.jsx
import logoSrc from "../../images/logo.png"
const logo = browser.runtime.getURL(logoSrc)
```

maybe add this to the documentation?

(want me to PR that?)

THanks again, you ROCK!

**Comment by fregante** [comment]
Glad you solved it, thanks for reporting back. It'd be great to have this piece of information on Parcel’s docs, which are somewhat lacking: https://parceljs.org/recipes/web-extension/

I added some extra links to the documentation https://github.com/fregante/browser-extension-template/commit/b311e54eb5368708ace4f0f9e368ec8116871e52
