### ISSUE TITLE
Need to restart the extension to see changes

### ISSUE THREAD

**Issue by goldylucks** [fregante/browser-extension-template#68]
When I make a change to a content script, I need to restart `$ web-ext run -t chromium` to see the changes.

repro repo
https://github.com/goldylucks/web-ext-reload-not-working

Thanks again for this project

**Comment by fregante** [comment]
Refer to the note: https://github.com/fregante/browser-extension-template#%EF%B8%8F-make-the-first-change

You don't need to restart it, just refresh the pace

**Comment by goldylucks** [comment]
I guess I wasn't clear, sry for that.

If I just refresh the page the changes aren't there.

**Comment by fregante** [comment]
Does web-ext pick up the changes? It should say "changes detected at (time)" or something like that

**Comment by goldylucks** [comment]
yes it says:
```
$ web-ext run -t chromium
Applying config file: ./package.json
Running web extension from /Users/Goldy/apps/web-extension/distribution
The extension will reload if any source file changes
Press R to reload (and Ctrl-C to quit)
Last extension reload: 18:54:04 GMT+0200 (Israel Standard Time)
```

**Comment by goldylucks** [comment]
can we reopen this?

**Comment by fregante** [comment]
If web-ext doesn't work for you, you can open an issue on their repo. Here it works as expected:

https://user-images.githubusercontent.com/1402241/159151167-4b2a96ac-df4c-44a7-9372-09a381742947.mov

**Comment by goldylucks** [comment]
"their" being parcel repo?

**Comment by fregante** [comment]
The reloading is managed by web-ext

**Comment by akash07k** [comment]
@fregante 
Any fix for this issue?
I'm also plagued by this :(
