### ISSUE TITLE
Unsafe construction of an any type value.

### ISSUE THREAD

**Issue by david-tejada** [fregante/browser-extension-template#69]
I'm getting this linting error in options-storage.ts. I want to use typescript and I just changed the files extensions to `.ts` like indicated. I also added `@sindresorhus/tsconfig` and `eslint-config-xo-typescript`. It's strange because if I hover over the error I get the type information. And if I assign the result of the call to `new OptionsSync({...})` to a variable and I hover over it I get the type information:

```
const options: OptionsSync<{
    colorRed: number;
    colorGreen: number;
    colorBlue: number;
    text: string;
}>
```

I don't know why it keeps saying that it is of type `any`

**Comment by david-tejada** [comment]
Another similar example, it's really strange because it clearly says that `colorRed` is of type `number`:

![Screenshot 2022-03-25T13-30-05 - Code](https://user-images.githubusercontent.com/3219671/160121325-e125c08d-5c24-4b42-b677-c575c6a77d14.png)

**Comment by fregante** [comment]
> I don't know why it keeps saying that it is of type `any`

I don't know either!  I was able to replicate the issue but it went away after I updated the [XO extension](https://marketplace.visualstudio.com/items?itemName=samverschueren.linter-xo) to v3.9.0. This is an IDE error, not a project error; Try running `npm run lint` and the error won't appear there.

Additionally make sure:

- you installed `typescript` itself in the project
- you created the tsconfig.json at the root of the project as suggested by `@sindresorhus/tsconfig`

**Comment by fregante** [comment]
<img width="673" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/160148252-704e21a3-d8b5-4ad7-b556-3e5818d64bf9.png">

**Comment by david-tejada** [comment]
Thanks for your help! In my case I also got the errors running `npm run lint`. I also hadn't install typescript in the project, but that didn't solve the issue. What I was missing was the `tsconfig.json` file. Once I created the file and reloaded the window all the  errors went away.

**Comment by aspiers** [comment]
A similar problem happens even with `tsconfig.json`, as described in #71.
