### ISSUE TITLE
Linting errors after converting to TypeScript

### ISSUE THREAD

**Issue by aspiers** [fregante/browser-extension-template#71]
If I follow the instructions for converting to TypeScript (including using `@sindresorhus/tsconfig`), `npm run lint` results in a load of errors:

```
  source/content.ts:4:8
  ✖   4:8   Unsafe assignment of an any value.                                                                                                                                 @typescript-eslint/no-unsafe-assignment
  ✖   4:24  Unsafe call of an any typed value.                                                                                                                                 @typescript-eslint/no-unsafe-call
  ✖   5:16  Operands of + operation with any is possible only with string, number, bigint or any                                                                               @typescript-eslint/restrict-plus-operands
  ✖   5:16  Operands of + operation with any is possible only with string, number, bigint or any                                                                               @typescript-eslint/restrict-plus-operands
  ✖   5:16  Operands of + operation with any is possible only with string, number, bigint or any                                                                               @typescript-eslint/restrict-plus-operands
  ✖   6:8   Unsafe assignment of an any value.                                                                                                                                 @typescript-eslint/no-unsafe-assignment
  ✖   8:2   Unsafe assignment of an any value.                                                                                                                                 @typescript-eslint/no-unsafe-assignment
  ✖  15:1   Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the void operator.  @typescript-eslint/no-floating-promises

  source/options.ts:2:8
  ✖   2:8   browser is defined but never used.                                                                                                                                 @typescript-eslint/no-unused-vars
  ✖   6:1   Unsafe call of an any typed value.                                                                                                                                 @typescript-eslint/no-unsafe-call
  ✖  13:40  Invalid type "any" of template literal expression.                                                                                                                 @typescript-eslint/restrict-template-expressions
  ✖  13:65  Invalid type "any" of template literal expression.                                                                                                                 @typescript-eslint/restrict-template-expressions
  ✖  13:90  Invalid type "any" of template literal expression.                                                                                                                 @typescript-eslint/restrict-template-expressions
  ✖  17:2   Unsafe assignment of an any value.                                                                                                                                 @typescript-eslint/no-unsafe-assignment

  source/options-storage.ts:undefined:undefined
  ✖   0:0   Parsing error: File @sindresorhus/tsconfig/tsconfig.json not found.                                                                                                

  15 errors
ERROR: "lint:js" exited with 1.
```

Some of these are trivial to fix, but I'm struggling to figure out how to address `@typescript-eslint/no-unsafe-assignment` and `eslint/no-unsafe-call` other than disabling those rules.  BTW I notice those are similar to the title of issue #69.

One very odd error is the last one (`Parsing error: File @sindresorhus/tsconfig/tsconfig.json not found`).  I have no idea what's going on here.  Even weirder - I thought I'd accidentally fixed it by changing `xo.envs` in `package.json` from `browser` to `webextensions` (which seems to be a more logical choice anyway, right?) ...  But then when I changed it back to `browser`, the parsing error didn't come back.  :man_shrugging:  

Anyway, you should be able to reproduce the exact list of errors above via this branch in my fork:

https://github.com/fregante/browser-extension-template/compare/main...aspiers:typescript

**Comment by david-tejada** [comment]
I got rid of those errors using this line to import browser:
```typescript
import * as browser from "webextension-polyfill";
```

**Comment by fregante** [comment]
The code is just demo code and it will have to be deleted. It doesn't have to be correct (especially for the lint)

That import you mentioned incorrect, what you're missing are the types for webextension-polyfill.

The last error is most likely a eslint cache error unfortunately, nothing I can fix.

**Comment by aspiers** [comment]
[**@fregante**](https://github.com/fregante) commented on [April 11, 2022 12:42 AM](https://github.com/fregante/browser-extension-template/issues/71#issuecomment-1094411570 "2022-04-10T23:42:52Z - Replied by Github Reply Comments"):
> The code is just demo code and it will have to be deleted. It doesn't have to be correct (especially for the lint)

True, but I am seeing the same errors from `@typescript-eslint/no-unsafe-assignment` and `@typescript-eslint/no-unsafe-call` in my own code after deletion of the demo code, which suggests that there may be some general issue with the combination of a) how the template's extension stack and its dependencies are configured, and b) how its linters are configured.  These complaints relating to implicit `any` types seem to indicate that there are some types not getting picked up by eslint.  But this is strange, because I can clearly see them in places like `node_modules/webext-options-sync/index.d.ts`.

> That import you mentioned incorrect, what you're missing are the types for webextension-polyfill.

You mean the import @david-tejada mentioned?  I just tried `npm add -D @types/webextension-polyfill` but it didn't eliminate any of the linting errors.  And if that is indeed needed in other circumstances, wouldn't it be worth mentioning in the `readme.md` in the paragraph about Typescript? 

> The last error is most likely a eslint cache error unfortunately, nothing I can fix.

Yeah, no worries - just thought I'd mention it in case you'd seen that weirdness before.

**Comment by david-tejada** [comment]
I can see now that importing browser like I did doesn't make any difference. I changed it back too `import browser from "webextension-polyfill";` and I get no errors. Maybe it was something that I did before adding `tsconfig.json` and seemed to work. Anyway, you can check out my [package.json](https://github.com/david-tejada/rango/blob/main/package.json) to see if you're missing something. I got no linting errors here

**Comment by fregante** [comment]
> True, but I am seeing the same errors from `@typescript-eslint/no-unsafe-assignment` and `@typescript-eslint/no-unsafe-call` in my own code after deletion of the demo code

Yeah that's unrelated to anything. Those are just lint rules, you can read their details on the `typescript-eslint` repo or you can disable them.

> wouldn't it be worth mentioning in the `readme.md` in the paragraph about Typescript?

Absolutely not, using TypeScript here assumes you already know TypeScript. Running `tsc` already tells you to install that package.
