### ISSUE TITLE
Source maps don't work by default

### ISSUE THREAD

**Issue by aspiers** [fregante/browser-extension-template#72]
If I add `console.log('foo');` to my `content.ts`, I see:

![image](https://user-images.githubusercontent.com/100738/162634370-8e119eb4-e36d-43f2-b791-2603308252ac.png)

but clicking on the `content.js:159` reveals a transpiled file rather than the original `content.js`.  This is presumably related to the warning immediately below it, which states that the `content.js.map` source map could not be loaded.  But why not?  What's the cause of the `ERR_BLOCKED_BY_CLIENT`, and can we fix it in the extension config?

I trawled the internet for answers, but it's full of useless suggestions, such as disabling source maps or removing the browser extension which causes the error.  Belatedly I found https://parceljs.org/recipes/web-extension/#hmr which says

> Source maps don't work unless inlined in web extensions

It doesn't explain *why* they don't work unless inlined, so I'm guessing it's a fundamental browser thing, e.g. a security restriction on extensions.

But anyway, I added this to `package.json`:

```json
    "targets": {
        "webext-dev": {
            "sourceMap": {
                "inline": true,
                "inlineSources": true
            }
        },
        "webext-prod": {}
    },
```

and also modified the `build` and `watch` scripts to include `--target webext-prod` and `--target webext-dev` respectively.

However this didn't *seem* to work *until* I eventually noticed that this actually changes the location of the generated `content.js` from `distribution/` to `distribution/webext-dev`, which means that the `web-ext run` command needs an extra option `-s distribution/webext-dev`.  And indeed `distribution/webext-dev/content.js` does have a source map inlined at the end of the file, and this not only gets rid of the `ERR_BLOCKED_BY_CLIENT` message, but gives correct mappings back to the true original source files.

If the above enhancement makes sense to you, I would propose including it so that source maps work by default.  It works for Typescript too.

BTW, even after all that, the results do not seem perfect.  For example, here's a stack trace from my extension:

![image](https://user-images.githubusercontent.com/100738/162635844-93fdd0ab-e2e8-400f-8e8d-af7b8e4e995a.png)

You can see that there are still references to `content.js` as well as the references to `.ts` files.  But perhaps that's because there are extra stack frames generated by the transpilation whose source code simply doesn't exist in the original Typescript.  So I guess I can't complain about those too much.

**Comment by aspiers** [comment]
[**@aspiers**](https://github.com/aspiers) commented on [April 10, 2022 8:16 PM](https://github.com/fregante/browser-extension-template/issues/72#issue-1199146893 "2022-04-10T19:16:58Z - Replied by Github Reply Comments"):
> > Source maps don't work unless inlined in web extensions
> 
> It doesn't explain *why* they don't work unless inlined, so I'm guessing it's a fundamental browser thing, e.g. a security restriction on extensions.

Did a bit more digging, and found:

- https://stackoverflow.com/questions/61462586/can-i-enable-sourcemaps-in-a-chrome-extension/62270410#62270410
- https://bugs.chromium.org/p/chromium/issues/detail?id=212374
- https://bugs.chromium.org/p/chromium/issues/detail?id=974543

so it seems this issue has been going on since 2013 in Chromium and derivatives, and is perhaps very recently fixed, or close to being fixed.

**Comment by fregante** [comment]
Thanks for the research. Yeah that's a Chrome limitation. Can you send a PR? The only change is that I'd just name them development and default, the latter is picked up automatically.

**Comment by aspiers** [comment]
[**@fregante**](https://github.com/fregante) commented on [April 11, 2022 1:03 AM](https://github.com/fregante/browser-extension-template/issues/72#issuecomment-1094417065 "2022-04-11T00:03:57Z - Replied by Github Reply Comments"):
> Thanks for the research. Yeah that's a Chrome limitation. Can you send a PR? The only change is that I'd just name them development and default, the latter is picked up automatically.

Sent - thanks for waiting patiently :-)

**Comment by fregante** [comment]
This has likely been fixed in the meanwhile:

- #87 

This is what I see now:

<img width="640" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/179708482-d221bfda-5dd6-4fe1-8af1-3cc70e373a95.png">

Unless I manually disable the source maps:

<img width="655" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/179708532-1cdac492-da76-499a-872f-c464a232058c.png">
