### ISSUE TITLE
Meta: Firefox deployment failed

### ISSUE THREAD

**Issue by fregante** [fregante/browser-extension-template#74]
@notlmn Could you follow the instructions in the failed action? The new terms must be approved.

**Comment by fregante** [comment]
Also I'm not seeing the extension in my Firefox account at all

**Comment by notlmn** [comment]
> @notlmn Could you follow the instructions in the failed action? The new terms must be approved.

Done!

> Also I'm not seeing the extension in my Firefox account at all

For some reason I don't see you added as author anymore on this extension. I added you (`b***c@gmail.com`) back in as owner, can you check again?
