### ISSUE TITLE
Chrome Web Store rejection for obfuscated code

### ISSUE THREAD

**Issue by andrewgy8** [fregante/browser-extension-template#84]
Hey! Thanks for the sweet boilerplate! Its been working really well so far. 

Just letting you know that I was rejected from CWS using this boilerplate yesterday for obfuscated code. 

> Hi there,
> 
> We regret to inform you that the most recent submission of your item was rejected. Please find the details below.
> 
> 
> Item name: Snippets
> 
> Item ID: eoeooehafnjjbkbnlbgfimnjchmadbap
> 
> Violation(s):
> 
> Code Readability Requirements
> 
> Violation reference ID: Red Titanium
> Violation: Having obfuscated code in the package.
> Violating content:
> Code snippet: options.c1ff580f.js:null:null: function $56fca9218aa06700$var$isCurrentPathname(path) {...
> How to rectify: Replace the obfuscated code with human-readable code and resubmit the item.
> Relevant section of the program policy:
> Developers must not obfuscate code or conceal functionality of their extension. [(learn more)](https://developer.chrome.com/webstore/program_policies#content_policies)

I had seen this issue you submitted https://github.com/parcel-bundler/parcel/issues/6092 

I didnt have any luck applying your suggestions. However, Im pending another review with `--no-scope-hoist` which seems to have removed the hexi from all the functions. Ill see if that works and report back...

Filing an issue incase others run into the same thing from CWS.

**Comment by fregante** [comment]
I think that our `mangle: false` setting in .terserrc is breaking the variable name shortening.

Dropping the scope hoisting probably produces more code but maybe it’s not a bad idea if it preserves the function names.

**Comment by fregante** [comment]
Does your extension work for you with that flag? It appears to break it: https://github.com/parcel-bundler/parcel/issues/8071#issuecomment-1120516568

**Comment by andrewgy8** [comment]
> Does your extension work for you with that flag?

Yeah, Ive just done a test and everything is working as expected so far. Takes around 2-3 days for my extension to be approved. Ill report back the results asap.

**Comment by andrewgy8** [comment]
Hey there! I can confirm that my extension has been published with the above fix, and it works as expected. To be absolutely explicit, here is my build command

`parcel build source/manifest.json --no-content-hash --no-source-maps --dist-dir distribution --no-scope-hoist --no-cache --detailed-report 0`
