### ISSUE TITLE
Include "popup" in template

### ISSUE THREAD

**Issue by AlecRust** [fregante/browser-extension-template#92]
Seems many (most?) browser extensions include a "popup" i.e. a small panel that appears when the icon is clicked:

![image](https://user-images.githubusercontent.com/247634/230373971-3574ccd2-2c4d-4fcf-b338-860386a91aaa.png)

I don't see mention of this browsing the code of this repo. Have you considered providing this by default or making it an option?

In most extensions I've browsed the code of I see `popup.css` and `popup.html` ([example](https://github.com/ajayyy/SponsorBlock/tree/master/public)).

**Comment by fregante** [comment]
This boilerplate doesn't intend to be a comprehensive one, but rather something to build on. Most of my extensions do not have a popup, for example. 

Thanks to Parcel, adding a popup is just a matter of creating popup.html and adding it to the manifest, and it's automatically picked up by the build, including any of its CSS and JS dependencies.
