### ISSUE TITLE
Icon greyed out and no functionality

### ISSUE THREAD

**Issue by Osiris-Team** [fregante/browser-extension-template#93]
I cloned the repo, made no modifications and loaded the extenstion into my browser, by loading it from the /distribution folder manually. 
However the icon is greyed out and no default functionality can be seen (like the console output or rgb panel)

**Comment by Osiris-Team** [comment]
Just noticed that the functionality is only for the options menu.
It would be great to have a basic example that modifies a websites html, by default too.

**Comment by Osiris-Team** [comment]
I am trying to execute the content script when loading google.com, however, it doesn't want to.
Changes:
```json
	"permissions": [
		"storage",
			"activeTab",
			"scripting"
	],
	"host_permissions": [
		"https://github.com/*"
	],
	"content_scripts": [
		{
			"matches": [ "https://google.com/*" ],
			"js": [ "content.js" ],
			"css": [ "content.css" ],
			"run_at": "document_end"
		}
	],
```
```js
console.log('💈 Content script loaded for', chrome.runtime.getManifest().name);
```
What am I missing @fregante

**Comment by fregante** [comment]
I suggest asking on StackOverflow or other forums. I built an extension with the template [yesterday](https://github.com/fregante/jdm) and it works. The issue is unrelated to this template

**Comment by Osiris-Team** [comment]
@fregante Ok will do that. But could there be maybe a second branch of this repo which modifies the html of a page?

**Comment by fregante** [comment]
It already happens, there's a content script specific to a page on github. Refer to the manifest
