### ISSUE TITLE
Nested folders in /src

### ISSUE THREAD

**Issue by pchr-srf** [fregante/browser-extension-template#98]
Hey, many thanks for the template, it's a very nice learning resource :)

What we are struggling with is having folders inside the /src directory, e.g. having a /src/options folder for all the options-related files. Is this possible?

**Comment by fregante** [comment]
I don’t think it's easily possible, but there might be some "namer" plugins to do that. See:

- https://github.com/parcel-bundler/parcel/issues/8963

**Comment by pchr-srf** [comment]
Alright, thanks for the quick answer!
